name: Link Check (report)

on:
  workflow_run:
    workflows: ["Link Check (analysis)"]
    types: [completed]

jobs:
  comment:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - name: Download Lychee output
        uses: actions/download-artifact@v4
        with:
          name: lychee-output
          run-id: ${{ github.event.workflow_run.id }}
          path: ${{ runner.temp }}/lychee-output

      - name: Comment on PR
        if: >
          github.event_name == 'workflow_run' &&
          github.event.workflow_run.conclusion == 'success'
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.workflow_run.pull_requests[0].number }}
          body-path: ${{ runner.temp }}/lychee-output/out.md
      
      - name: Create Issue From File
        if: github.event_name == 'workflow_dispatch'
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: Link Checker Report
          content-filepath: ${{ runner.temp }}/lychee-output/out.md
          labels: report, automated issue